THIS_DIR=`pwd`

mkdir $LLVM_RELEASE_DIR
mkdir llvm/build
pushd llvm/build

cmake .. \
	-DCMAKE_INSTALL_PREFIX=$THIS_DIR/$LLVM_RELEASE_DIR \
	-DHAVE_SANITIZER_MSAN_INTERFACE_H=0 \
	-DLLVM_BUILD_32_BITS=$LLVM_BUILD_32_BITS \
	-DLLVM_TARGETS_TO_BUILD=X86 \
	-DLLVM_ENABLE_TERMINFO=OFF \
	-DLLVM_ENABLE_ZLIB=OFF \
	-DLLVM_INCLUDE_DOCS=OFF \
	-DLLVM_INCLUDE_EXAMPLES=OFF \
	-DLLVM_INCLUDE_TESTS=OFF \
	-DLLVM_INCLUDE_TOOLS=OFF \
	-DLLVM_INCLUDE_UTILS=OFF

make
make install

popd
