LLVM_VERSION=4.0.0
LLVM_TAR=llvm-$LLVM_VERSION.src.tar.xz
LLVM_URL=http://releases.llvm.org/$LLVM_VERSION/$LLVM_TAR

if [ $TRAVIS_OS_NAME == "osx" ]; then
	CPU_SUFFIX=
	CC_SUFFIX=
else
	CPU_SUFFIX=-$TARGET_CPU
	CC_SUFFIX=-$CC
fi

if [ $TARGET_CPU == "x86" ]; then
	LLVM_BUILD_32_BITS=ON
else
	LLVM_BUILD_32_BITS=OFF
fi

# packing a debug build with xz takes too much time, travis ci times out

if [ $BUILD_CONFIGURATION == "Debug" ]; then
	DEBUG_SUFFIX=-dbg
	TAR_COMPRESSION=z
	TAR_FILE_EXT=.gz
else
	DEBUG_SUFFIX=
	TAR_COMPRESSION=J
	TAR_FILE_EXT=.xz
fi

THIS_DIR=`pwd`
LLVM_RELEASE_NAME=llvm-$LLVM_VERSION-$TRAVIS_OS_NAME$CPU_SUFFIX$CC_SUFFIX$DEBUG_SUFFIX
LLVM_RELEASE_DIR=$THIS_DIR/$LLVM_RELEASE_NAME
LLVM_RELEASE_FILE=$LLVM_RELEASE_NAME.tar$TAR_FILE_EXT

CMAKE_FLAGS=(
	-DCMAKE_INSTALL_PREFIX=$LLVM_RELEASE_DIR
	-DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION
	-DLLVM_BUILD_32_BITS=$LLVM_BUILD_32_BITS
	-DLLVM_TARGETS_TO_BUILD=X86
	-DLLVM_ENABLE_TERMINFO=OFF
	-DLLVM_ENABLE_ZLIB=OFF
	-DLLVM_INCLUDE_DOCS=OFF
	-DLLVM_INCLUDE_EXAMPLES=OFF
	-DLLVM_INCLUDE_TESTS=OFF
	-DLLVM_INCLUDE_TOOLS=OFF
	-DLLVM_INCLUDE_UTILS=OFF
	)

CMAKE_FLAGS=${CMAKE_FLAGS[*]}

